language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - 'master'

install:
    - composer update

script: phpunit --verbose --debug --bootstrap tests/bootstrap.php tests
